// Generated by CoffeeScript 1.12.4
(function() {
  var faasFunction, getStdin;

  getStdin = require('get-stdin');

  faasFunction = require('./function/function');

  getStdin().then(function(request) {
    return faasFunction(request);
  }).then(console.log)["catch"](console.log.bind(console));

}).call(this);
